config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :activities, only: [ :index, :new, :show, :create ] do
    resources :bookings, only: [ :create ]
  end
  resources :bookings, only: [ :index ]

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :seller, class_name: 'User'
  has_many :bookings
  mount_uploader :photo, PhotoUploader
  validates :name, :address, :type_activity, :price, :description, presence: true
  validates :max_participants, :seller, presence: true
  validates :price, :max_participants, numericality: { only_integer: true }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :activity
  validates :date, presence: true
  validates :user, presence: true
  validates :activity, presence: true
  validates :total_price, presence: true
  validates :participants_number, presence: true
  validates :status, inclusion: { in: %w[pending accepted declined] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and
  has_many :activities, dependent: :destroy, foreign_key: :seller_id
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: %i[facebook google]
  validates :first_name, :last_name, :phone, :address, :email, presence: true
  validates :email, format: { with: /[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)/ }
  validates :email, uniqueness: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @activities = Activity.where.not(latitude: nil, longitude: nil)

    @markers = @activities.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { activity: activity })
      }
    end

    if params[:location]
      @activities = policy_scope(Activity).where('address LIKE ?', "%#{params[:location]}%")
    else
      @activities = policy_scope(Activity).order(created_at: :desc)
    end
  end

  def new
    @activity = Activity.new
    authorize @activity
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.seller = current_user
    authorize @activity
    if @activity.save
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  def show
    @activity = Activity.find(params[:id])
    authorize @activity
    @booking = Booking.new
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :address, :price, :type_activity, :description, :max_participants, :location, :latitude, :longitude, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :phone])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_infowindow.html.erb
<p>test</p>

app/views/activities/index.html.erb
<!-- <h1 class="text-center">Activities in <%# params[:location].nil? ? return params[:location].capitalize : "all" %></h1> -->
<% if params[:location] != "" %>
<h1 class="text-center"> Activities in <%= params[:location] %></h1>
<% elsif params[:location] == "" || params[:location].nil? %>
<h1 class="text-center"> All activities</h1>
<% end %>
<h2 class="text-center mb-4">Choose wich activity you want to do</h2>

<div class="new-search d-flex justify-content-center">
    <form action='activities' method='get' class='d-flex align-items-center'>
      <input id='search' name='location' type='text' placeholder='Location' class='font-italic' style="padding: 10px;width: 300px;margin: 20px;" />
      <input type='submit' class="btn btn-outline-success btn-lg rounded" value="New search" style="max-height:48px;">
    </form>
  </div>
<div class="index-activities-container d-flex justify-content-around ml-auto mr-auto">
  <div class="container d-flex justify-content-around mt-4">
    <div
      id="map"
      style="width: 100%;
      height: 600px;
      margin: 0px 8px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
  <div class="activities_list cards color_white text-center">
    <% @activities.each do |activity| %>
    <%= link_to activity_path(activity) do%>
    <div class="card-category" style="background-image:
         url('<%= cl_image_path activity.photo, height: 300, width: 400, crop: :fill %>'); box-shadow: 0 0 15px rgba(0,0,0,0.2);">
      <div class="activity-title d-flex justify-content-between align-items-center pl-3 pr-3" style="height: 60px;">
        <h6 style="min-width: 120px; "><%= activity.name %></h6>
        <span><%= activity.type_activity %></span>
      </div>
      <div class="card_bottom_info d-flex justify-content-between align-items-center">
        <p id="nb-people"><%= activity.max_participants %> place(s)</p>
        <p id="price"><%= activity.price %> €/pers</p>
      </div>
    </div>
    <%end%>
    <% end %>
  </div>
</div>

app/views/activities/new.html.erb
    <div class="container-new-activity">
    <h1>New activity</h1>
    <div class="d-flex">
      <div class="col-md-6">
        <%= simple_form_for @activity do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :max_participants %>
        <%= f.input :address %>
        <%= f.input :type_activity, collection: ["Outdoor", "Indoor"] %>
      </div>
         <div class="col-md-4">
           <%= f.input :start_date, type: :date %>
           <%= f.input :end_date, type: :date %>
           <%= f.input :photo %>
           <%= f.input :photo_cache, as: :hidden %>
           <%= f.button :submit, class: "btn btn-outline-primary" %>
        <% end %>

       <!--    <div class="form-group">
         <label>Upload Image</label>
         <div class="input-group">
           <span class="input-group-btn">
             <span class="btn btn-default btn-file">
               Upload your pictures<input type="file" id="imgInp">
             </span>
           </span>
         </div>
         <img id='img-upload'/>
       </div>
               </div> -->


      </div>
    </div>
    </div>

app/views/activities/show.html.erb
<div class="p-5">
<!-- <p><%= link_to "Back", activities_path %></p>--><div class="container-show d-flex p-4">
  <div class="container-activity d-flex aligh-items-end mx-3">
    <div class="card rounded" style="width: 25rem; border-radius: 4px important!">
      <div class="card-body">
        <div class="d-flex w-100 justify-content-between">
          <h5><%= @activity.name %></h5>
          <h5><%= @activity.type_activity %></h5>
        </div>
          <h6 class="mb-2 text-muted"><i class="fas fa-map-marker-alt"></i> <%= @activity.address %>/h6>
          <div class="d-flex flex-column justify-content-between">
          <p style="min-height: 150px; margin-top: 20px; color: black;"><%= @activity.description %></p>
          <% if policy(Activity).index? %>
            <%= link_to "Back to my bookings", bookings_path %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container-activity-photo d-flex flex-column">
        <div>
          <div class="img-details d-flex aligh-items-end justify-content-between w-100 mx-2 px-2">
              <p>Max: <%= @activity.max_participants %> <i class="fas fa-user-friends"></i></p>
              <!-- <p>Price: <%= @activity.price %> €/pers</p> -->
          </div>
        </div>
        <%= cl_image_tag @activity.photo, height: 260, width: 287, crop: :fill %>
    </div>
  </div>

  <div class="container-new-booking">

    <div class="form-container h-100">

      <div class="header">
        <div class="header-row">
          <div class="big-bold" id="price" data-amount-cents="1"><%= @activity.price %>€</div>
          <div class="small-light"> / PARTICIPANT</div>
        </div>
      </div>

    <%= simple_form_for([@activity, @booking]) do |f| %>
      <%= f.input :date, type: :date %>

      <div class="flex-between mt-4">
        Participants:
        <div class="actions">
          <btn href="#" class="btn round-bordered incrementer minus" disabled data-offset="-1">-</btn>
          <span id="counter" data-count="1">1</span>
          <btn href="#" class="btn round-bordered incrementer plus" data-offset="1">+</btn>
        </div>
      </div>
      <%= f.input :participants_number, as: :hidden %>

      <div id="total-price" class="mb-4">Total price: <strong><%= @activity.price %>€ </strong></div>
      <%# f.input :date, :as => :string, :input_html => { :class => 'date_picker' } %>
      <%= f.button :submit, class: 'btn btn-outline-success' %>
    <% end %>

    </div>

  </div>
</div>


<%= javascript_pack_tag 'plusminus' %>

app/views/bookings/index.html.erb
<div class="container p-4">

<% @bookings.each do |booking| %>
<div class="card-product card-product-margin-content">
  <%= cl_image_tag booking.activity.photo, height: 300, width: 400, crop: :fill %>
  <div class="card-product-infos">
    <h2><%= booking.activity.name %></h2>
    <div class="card-product-infos-details">
    <p>Date: <%= booking.date.strftime("%Y-%d-%m") %></p>
    <p> <%= booking.participants_number %> <i class="fas fa-user-friends"></i></p>
    <p> Total price: <%= booking.total_price %>€</p>
    </div>
  </div>
  <div class="card-product-status">
    <h2>
      <% if booking.status == "pending" %>
      <i class="fas fa-hourglass-half"></i>
      <% elsif booking.status == "confirmed" %>
        <i class="fas fa-check"></i>
        <% else %>
        <i class="far fa-times-circle"></i>
      <% end %>
      <%= booking.status.capitalize %></h2>
      <p> <%= link_to "View activity", activity_path(booking.activity) %></p>
  </div>
</div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ActnB</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
     <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="banner">
    <div class="d-flex align-items-center justify-content-around">
      <div>
        <h1><b>Welcome to actbnb</b></h1>
        <p>Réservez des activités pour vivre des expériences uniques</p>
      </div>
      <%= image_tag 'travelers.png', class:'rounded float-right img-home', style:'height: 400px; width: 400px'%>
    </div>
  </div>
  <div class="search-hp">
    <form action='activities' method='get' class='d-flex align-items-center'>
      <input id='search' name='location' type='text' placeholder='Location' class='font-italic' style="padding: 10px;width: 300px;margin: 20px;" />
      <input type='submit' class="btn btn-outline-success btn-lg rounded" value="Find activities !" style="max-height:48px;">
    </form>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://branditprintit.com/wp-content/uploads/2017/04/logo-degin-logo-design-design-art-free.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "New activity", new_activity_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Search", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <% if policy(Activity).index? %>
          <%= link_to "Activities", activities_path, class: "nav-link" %>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to "Bookings", bookings_path, class: "nav-link" %>
      </li>

      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <%= image_tag 'avatar.jpg', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "", "#", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, render: root_path, class: "dropdown-item" %>
        </div>
      </li>

      <% else %>
      <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        </li>
          <li class="nav-item active">
          <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
        </li>
      </ul>

      <% end %>
    </ul>
  </div>
</div>